In [1]:
import torch

### `requires_grad`

* https://pytorch.org/docs/stable/generated/torch.Tensor.requires_grad_.html

In [2]:
x=torch.randn(3 , requires_grad=True).sum() #tensor con 3 valore random
y=x+2
print(y)

tensor(-0.5583, grad_fn=<AddBackward0>)


In [3]:
y = torch.tensor( x + 2,requires_grad=True)

C:\Users\Fernando Celis\AppData\Local\Temp\ipykernel_11476\1293865451.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x+2,requires_grad=True)


In [6]:
x = torch.tensor(9.0,requires_grad=True)
y = x + 2
z = y**2 
z = (x+2)**2
z.backward() 
print(x.grad, y.grad)

tensor(22.) None


C:\Users\Fernando Celis\AppData\Local\Temp\ipykernel_11476\2906174535.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:491.)
  print(x.grad, y.grad)


$$\frac{\partial{(y)}}{\partial w} = \frac{\partial}{\partial w} (w *3 +5) = 3 $$

In [42]:
x=torch.randn(3 , requires_grad=True)
x
z = x+2 
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [26]:
x = torch.tensor(3)

# create tensors with requires_grad = true
w = torch.tensor(2, requires_grad = True)
b = torch.tensor(5.0, requires_grad = True)

# print the tensors
print("x:", x)
print("w:", w)
print("b:", b)

# define a function y for the above tensors
y = w*x + b
print("y:", y)

# Compute gradients by calling backward function for y
y.backward()

# Access and print the gradients w.r.t x, w, and b
dx = x.grad
dw = w.grad
db = b.grad
print("x.grad :", dx)
print("w.grad :", dw)
print("b.grad :", db)


RuntimeError: Only Tensors of floating point and complex dtype can require gradients

Las siguientes funciones desactivan el gradiente:
* x.requires_grad_(false)
* x.detach()                => crea un nuevo vector con los mismos valores sin gradiente
* with torch.no_grad():


In [8]:
x2=torch.randn(3,requires_grad=True)
print(x2)
x2.requires_grad_(False)
print(x2)

tensor([ 0.3222, -0.1314,  1.0303], requires_grad=True)
tensor([ 0.3222, -0.1314,  1.0303])


In [12]:
x2=torch.randn(3,requires_grad=True)
x2.detach
print(x2+2)
#print(x2.detach())


tensor([1.5915, 3.7555, 0.2695], grad_fn=<AddBackward0>)


In [13]:
x2=torch.randn(3,requires_grad=True)
c = x2+x2
print(c)

tensor([-0.2779,  1.9586,  0.4510], grad_fn=<AddBackward0>)


In [14]:
x2=torch.randn(3,requires_grad=True)
with torch.no_grad():
    print(x2)
    a= x2+x2
    print(a)

tensor([ 0.6409, -0.4536, -0.6829], requires_grad=True)
tensor([ 1.2818, -0.9072, -1.3657])


In [18]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
  model_output=(weights*3).sum()
  model_output.backward()  #acumula

  print(weights.grad)

  #weights.grad.zero_() #reinicia el gradiente

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [19]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0,requires_grad=True)

#forward and loss
y_hat= w*x
loss= (y_hat - y)**2

print(loss)

#backward
loss.backward() #calcula el gradiente
print(w.grad)


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


### ejercicio

In [22]:
#f = 2*x

X = torch.tensor([1,2,3,4],dtype=torch.float32)
Y = torch.tensor([2,4,6,8],dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True) 

#model predict
def forward(x):
  return w*x

#loss =MSE
def loss(y,y_predicted):
  return ((y_predicted-y)**2).mean()

print(f'prediction before training: f(5)={forward(5):.3f}')

#training
learning_rate=0.01
n_iters=100

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad

    # zero the gradients after updating
    w.grad.zero_()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.8f}')

print(f'Prediction after training: f(5) = {forward(5).item():.3f}')


    

prediction before training: f(5)=0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


### Métricas

* https://torchmetrics.readthedocs.io/en/stable/classification/confusion_matrix.html?highlight=confusion


In [27]:
import torch
import torchmetrics
from torchmetrics import ConfusionMatrix

import numpy as np
from sklearn.metrics import multilabel_confusion_matrix, confusion_matrix, accuracy_score, precision_score, recall_score

In [28]:
torch.manual_seed(6)
#Inicialize the binary randomic values
binary_samples = 20
binary_classes = 2
binary_output = torch.randn(binary_samples, binary_classes)
binary_pred = torch.argmax(binary_output, 1)

binary_target = torch.randint(0, high = binary_classes, size = (binary_samples,))
print(f'Predict: {binary_pred}')
print(f'Target:  {binary_target}')

Predict: tensor([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1])
Target:  tensor([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1])


In [29]:
#Create the confusion matrix and each TP, TN, FP and FN of the distribution
binary_confmat = ConfusionMatrix(num_classes = 2, task="binary")

binary_cm = binary_confmat(binary_pred, binary_target)
print(f'Pytorch confusion matrix: \n {binary_cm} \n')
[binary_TN, binary_FP], [binary_FN, binary_TP] =  binary_confmat(binary_pred, binary_target)
print('TP {}, TN {}, FP {}, FN {}'.format(binary_TP, binary_TN, binary_FP, binary_FN))

Pytorch confusion matrix: 
 tensor([[5, 4],
        [2, 9]]) 

TP 9, TN 5, FP 4, FN 2


<div style="text-align:center">
  <img src="img/Confusion-matrix-and-performance-equations.png" alt="dim" width="80%">
</div>


In [30]:
# Calculating each metric by myself

binary_accuracy = (binary_TP + binary_TN) / (binary_TP + binary_FP + binary_TN + binary_FN)
binary_accuracy_cm = np.sum(np.diag(binary_cm)/np.sum(binary_cm.numpy()))

print(' Binary accuracy: {} \n Using confussion matrix: {}'.format(binary_accuracy, binary_accuracy_cm))

binary_precision   = binary_TP / (binary_TP + binary_FP)
binary_sensitivity = binary_TP / (binary_TP + binary_FN)
binary_specificity = binary_TN / (binary_TN + binary_FP)

print(' Precision: {} \n Sensitivity: {} \n Specificity: {}'.format(binary_precision, binary_sensitivity, binary_specificity))

 Binary accuracy: 0.699999988079071 
 Using confussion matrix: 0.7
 Precision: 0.692307710647583 
 Sensitivity: 0.8181818127632141 
 Specificity: 0.5555555820465088


In [31]:
#sk-learn metrics
b_acc = accuracy_score(binary_target, binary_pred)
b_pre = precision_score(binary_target, binary_pred)
b_rec = recall_score(binary_target, binary_pred)
print(' Accuracy: {} \n Precision: {} \n Sensitivity: {} \n'.format(b_acc, b_pre, b_rec))

 Accuracy: 0.7 
 Precision: 0.6923076923076923 
 Sensitivity: 0.8181818181818182 



In [32]:
torch.manual_seed(0)
#Inicialize the multi-class randomic values
nb_samples = 20
nb_classes = 4
mc_output = torch.randn(nb_samples, nb_classes)
mc_pred = torch.argmax(mc_output, 1)
mc_target = torch.randint(0, high = nb_classes, size = (nb_samples,))
print(f'Predict: {mc_pred}')
print(f'Target:  {mc_target}')

Predict: tensor([2, 0, 2, 1, 3, 3, 0, 1, 3, 2, 1, 1, 2, 2, 3, 2, 3, 1, 2, 1])
Target:  tensor([2, 3, 0, 1, 1, 3, 1, 1, 3, 2, 3, 3, 2, 2, 3, 0, 2, 3, 1, 0])


In [34]:
mc_conf_matrix = torch.zeros(nb_classes, nb_classes)
for t, p in zip(mc_target, mc_pred):
    print(t,p)
    mc_conf_matrix[t, p] += 1
    print(mc_conf_matrix)
print(f'Pytorch confusion matrix: \n {mc_conf_matrix} \n')

tensor(2) tensor(2)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]])
tensor(3) tensor(0)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]])
tensor(0) tensor(2)
tensor([[0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]])
tensor(1) tensor(1)
tensor([[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]])
tensor(1) tensor(3)
tensor([[0., 0., 1., 0.],
        [0., 1., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]])
tensor(3) tensor(3)
tensor([[0., 0., 1., 0.],
        [0., 1., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 1.]])
tensor(1) tensor(0)
tensor([[0., 0., 1., 0.],
        [1., 1., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 1.]])
tensor(1) tensor(1)
tensor([[0., 0., 1., 0.],
        [1., 2., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 1.]])


In [33]:
# Pytorch confusion matrix
mc_conf_matrix = torch.zeros(nb_classes, nb_classes)
for t, p in zip(mc_target, mc_pred):
    mc_conf_matrix[t, p] += 1
print(f'Pytorch confusion matrix: \n {mc_conf_matrix} \n')

mc_confmat = ConfusionMatrix(num_classes = 4,task="multiclass")
print(f'Pytorch confusion matrix: \n {mc_confmat(mc_pred, mc_target)} \n')


# Sklearn confusion matrix
mc_cm = confusion_matrix(mc_target.flatten(), mc_pred.flatten(), labels=[0,1,2,3])
print(f'Sklearn multi-label confusion matrix\n  {mc_cm} \n')

Pytorch confusion matrix: 
 tensor([[0., 1., 2., 0.],
        [1., 2., 1., 1.],
        [0., 0., 4., 1.],
        [1., 3., 0., 3.]]) 

Pytorch confusion matrix: 
 tensor([[0, 1, 2, 0],
        [1, 2, 1, 1],
        [0, 0, 4, 1],
        [1, 3, 0, 3]]) 

Sklearn multi-label confusion matrix
  [[0 1 2 0]
 [1 2 1 1]
 [0 0 4 1]
 [1 3 0 3]] 



In [36]:
# Pytorch TP - TN - FP - FN for each class
mc_TP = mc_conf_matrix.diag()
for c in range(nb_classes):
    idx = torch.ones(nb_classes).byte()
    idx[c] = 0
    # all non-class samples classified as non-class
    mc_TN = mc_conf_matrix[idx.nonzero()[:, None], idx.nonzero()].sum() 
    # all non-class samples classified as class
    mc_FP = mc_conf_matrix[idx, c].sum()
    # all class samples not classified as class
    mc_FN = mc_conf_matrix[c, idx].sum()
    
    print('Class {}\nTP {}, TN {}, FP {}, FN {}'.format(
        c, mc_TP[c], mc_TN, mc_FP, mc_FN))
    
    

Class 0
TP 0.0, TN 15.0, FP 2.0, FN 3.0
Class 1
TP 2.0, TN 11.0, FP 4.0, FN 3.0
Class 2
TP 4.0, TN 12.0, FP 3.0, FN 1.0
Class 3
TP 3.0, TN 11.0, FP 2.0, FN 4.0


C:\Users\Fernando Celis\AppData\Local\Temp\ipykernel_11476\250390074.py:9: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at ..\aten\src\ATen/native/IndexingUtils.h:28.)
  mc_FP = mc_conf_matrix[idx, c].sum()
C:\Users\Fernando Celis\AppData\Local\Temp\ipykernel_11476\250390074.py:11: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at ..\aten\src\ATen/native/IndexingUtils.h:28.)
  mc_FN = mc_conf_matrix[c, idx].sum()


In [37]:
#Sklearn  TP - TN - FP - FN for each class
cm_ml = multilabel_confusion_matrix(mc_target, mc_pred)
print('Sklearn multi-label confusion matrix\n', cm_ml)

Sklearn multi-label confusion matrix
 [[[15  2]
  [ 3  0]]

 [[11  4]
  [ 3  2]]

 [[12  3]
  [ 1  4]]

 [[11  2]
  [ 4  3]]]


TorchMetrics es una colección nativa de PyTorch de código abierto de métricas funcionales y modulares para evaluaciones simples de rendimiento. Hasta ahora se han implementado métricas manualmente y con sklearn. La información necesaria para implementar estas métricas se encuentran en su documentación.


* https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html 
* https://torchmetrics.readthedocs.io/en/stable/classification/precision.html
* https://torchmetrics.readthedocs.io/en/stable/classification/recall.html

In [38]:
torch.manual_seed(0)
#Inicialize the multi-class randomic values
nb_samples = 20
nb_classes = 4
mc_output = torch.randn(nb_samples, nb_classes)
mc_pred = torch.argmax(mc_output, 1)
mc_target = torch.randint(0, high = nb_classes, size = (nb_samples,))
print(f'Predict: {mc_pred}')
print(f'Target:  {mc_target}')

Predict: tensor([2, 0, 2, 1, 3, 3, 0, 1, 3, 2, 1, 1, 2, 2, 3, 2, 3, 1, 2, 1])
Target:  tensor([2, 3, 0, 1, 1, 3, 1, 1, 3, 2, 3, 3, 2, 2, 3, 0, 2, 3, 1, 0])


In [40]:
from torchmetrics.classification import MulticlassAccuracy
accuracy = MulticlassAccuracy(task="multiclass", num_classes=4)
accuracy(mc_pred, mc_target)



tensor(0.4071)

In [41]:
from torchmetrics.classification import MulticlassRecall


metric = MulticlassRecall(num_classes=4)
metric(mc_pred, mc_target)

tensor(0.4071)